# 주문량이 많은 아이스크림들 조회하기

# CASE 1
SELECT FLAVOR
FROM (
    SELECT 
        SHIPMENT_ID
        ,FLAVOR
        ,TOTAL_ORDER
    FROM FIRST_HALF
    UNION ALL
    SELECT 
        SHIPMENT_ID
        ,FLAVOR
        ,TOTAL_ORDER
    FROM JULY
) AS T
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3
