# level 4 
# 주문량이 많은 아이스크림들 조회하기
# MySQL
# https://school.programmers.co.kr/learn/courses/30/lessons/133027

# CASE 1
SELECT FLAVOR
FROM (
    SELECT 
        SHIPMENT_ID
        ,FLAVOR
        ,TOTAL_ORDER
    FROM FIRST_HALF
    UNION ALL
    SELECT 
        SHIPMENT_ID
        ,FLAVOR
        ,TOTAL_ORDER
    FROM JULY
) AS T
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3

# CASE 2
SELECT
    FLAVOR
FROM (
    SELECT 
        JULY.SHIPMENT_ID
        ,JULY.FLAVOR
        ,SUM(JULY.TOTAL_ORDER + IFNULL(HALF.TOTAL_ORDER,0)) AS TOTAL_ORDER
    FROM JULY AS JULY
    LEFT JOIN FIRST_HALF AS HALF
    ON JULY.SHIPMENT_ID = HALF.SHIPMENT_ID
    GROUP BY JULY.FLAVOR
)AS T
ORDER BY TOTAL_ORDER DESC
LIMIT 3
