# lv4 select
# 오프라인/온라인 판매 통합
# https://school.programmers.co.kr/learn/courses/30/lessons/131537

SELECT 
  DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE
  , PRODUCT_ID
  , USER_ID
  , SALES_AMOUNT
FROM (
    SELECT 
      SALES_DATE
      , PRODUCT_ID
      , USER_ID
      , SALES_AMOUNT
    FROM ONLINE_SALE 
    WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
    UNION ALL
    SELECT 
      SALES_DATE
      , PRODUCT_ID
      , NULL AS USER_ID
      , SALES_AMOUNT
    FROM OFFLINE_SALE 
    WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
) AS T
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC
