#level4 select 서울에 위치한 식당 목록 출력

SELECT 
  RI.REST_ID
  ,RI.REST_NAME
  ,RI.FOOD_TYPE
  ,RI.FAVORITES
  ,RI.ADDRESS
  ,ROUND(AVG(RV.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS RI
INNER JOIN REST_REVIEW AS RV
ON RI.REST_ID = RV.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC
