# lv4 join 5월 식품 총매출 조회
# https://school.programmers.co.kr/learn/courses/30/lessons/131117

SELECT 
    FO.PRODUCT_ID
    ,FP.PRODUCT_NAME
    ,SUM(FO.AMOUNT * FP.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS FP
INNER JOIN FOOD_ORDER AS FO
ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE FO.PRODUCE_DATE >= '2022-05-01'
    AND FO.PRODUCE_DATE < '2022-06-01'
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
