# lv4 join 그룹별 조건에 맞는 식당 찾기
#https://school.programmers.co.kr/learn/courses/30/lessons/131124

# CASE 1
SELECT 
  MP.MEMBER_NAME
  ,REVIEW.REVIEW_TEXT
  ,DATE_FORMAT(REVIEW.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS MP
INNER JOIN REST_REVIEW AS REVIEW
ON MP.MEMBER_ID = REVIEW.MEMBER_ID
WHERE MP.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC 
    LIMIT 1
)
ORDER BY REVIEW.REVIEW_DATE, REVIEW.REVIEW_TEXT ASC
;
